[book]
authors = ["DingVero"]
language = "zh"
src = "src"
title = "考研408笔记"
description = ""

[build]
create-missing = false

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/DingWH03/note-408"
edit-url-template = "https://github.com/DingWH03/note-408/edit/master/{path}"
input-404 = "404.md"
site-url =  "https://408.note.cxhap.top/"
cname = "408.note.cxhap.top"

[output.html.fold]
enable = true
level = 1
